handle documented cases in Schema annotation
SMILEY4/schema-kenerator pull request #31
Opened 2024-10-11 12:11 UTC by NecroKote

- `minLength` and `maxLength` are ignored if the value is below 0
- `minLength` and `maxLength` are not included for anything other than `string` type
- `format` is included only if it's not blank

Closes #29

2024-10-11 13:50 UTC, rmcmk requested changes
Hey -- nice fix. Just wanted to point out there are a two more `@Schema` fields that kenerator supports, with non-respected ignore conditions. Apologies, I probably should have stated all affected schema attributes in #29  

```java
    /**
     * Sets the minimum numeric value for a property.  Ignored if the value is an empty string or not a number.
     *
     * @return the minimum value for this schema
     **/
    String minimum() default "";
    
    
    /**
     * Sets the minimum numeric value for a property.  Ignored if the value is an empty string or not a number.
     *
     * @return the minimum value for this schema
     **/
    String minimum() default "";
```

2024-10-11 14:38 UTC, NecroKote commented
re: `minimum` and `maximum` - those are already covered by existing `.filter { it.isNotBlank() }`
At least for the "Ignored if the value is an empty string" part

2024-10-11 15:28 UTC, rmcmk commented
:facepalm: Looked at this code half a dozen times and missed that LOL. Guess that only leaves the number validation bit. Not sure if that is necessary, though.

2024-10-12 16:13 UTC, SMILEY4 commented
Looks good to me  :+1:    Thank you!
If its ready i'll merge it.

2024-10-12 21:59 UTC, NecroKote commented
Please do!

2024-10-13 09:44 UTC, merged